from models.request import AnalyzedRequest
from models.risk import RiskAnalysis


class RiskScorer:
    """
    Calculates an overall security risk score based on
    the findings generated by the SecurityAnalyzer.
    """

    SEVERITY_SCORES = {
        "Info": 0,
        "Low": 5,
        "Medium": 15,
        "High": 30,
        "Critical": 50,
    }

    def analyze(self, request: AnalyzedRequest) -> AnalyzedRequest:
        """
        Calculate the overall risk score and recommendations.
        """

        score = 0

        for finding in request.security.findings:
            score += self.SEVERITY_SCORES.get(
                finding.severity,
                0
            )

        # Cap score at 100
        score = min(score, 100)

        # Determine risk level
        if score <= 20:
            level = "Low"

        elif score <= 50:
            level = "Medium"

        elif score <= 80:
            level = "High"

        else:
            level = "Critical"

        recommendations = self._generate_recommendations(request)

        summary = (
            f"{level} risk ({score}/100). "
            f"{len(request.security.findings)} security finding(s) detected."
        )

        request.risk = RiskAnalysis(
            score=score,
            level=level,
            recommendations=recommendations,
            summary=summary,
        )

        return request

    def _generate_recommendations(
        self,
        request: AnalyzedRequest,
    ) -> list[str]:
        """
        Generate recommendations based on detected findings.
        """

        recommendations = []

        finding_titles = {
            finding.title
            for finding in request.security.findings
        }

        if "Insecure Transport" in finding_titles:
            recommendations.append(
                "Use HTTPS instead of HTTP for all communication."
            )

        if "Sensitive Header: Authorization" in finding_titles:
            recommendations.append(
                "Protect Authorization headers and avoid logging them."
            )

        if "Sensitive Header: Cookie" in finding_titles:
            recommendations.append(
                "Use Secure and HttpOnly cookie attributes where applicable."
            )

        if "Sensitive Query Parameter" in finding_titles:
            recommendations.append(
                "Avoid passing tokens or API keys through URL parameters."
            )

        if "Missing Security Headers" in finding_titles:
            recommendations.append(
                "Configure standard HTTP security headers."
            )

        if "File Upload Endpoint" in finding_titles:
            recommendations.append(
                "Validate uploaded files, restrict MIME types, and scan for malware."
            )

        if "State-Changing Request" in finding_titles:
            recommendations.append(
                "Ensure authorization and input validation before modifying resources."
            )

        if "Large Cookie Collection" in finding_titles:
            recommendations.append(
                "Reduce unnecessary cookies to minimize request size."
            )

        if "Server Error" in finding_titles:
            recommendations.append(
                "Investigate server-side errors and avoid exposing internal details."
            )

        if not recommendations:
            recommendations.append(
                "No major security improvements are required."
            )

        return recommendations